version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gocritic
    - nolintlint
    - bodyclose
    - durationcheck
    - errorlint
    - makezero
    - nilerr
    - predeclared
    - revive
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: US
